# Generated by Django 2.1.4 on 2018-12-20 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('time', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('link', models.URLField(null=True, verbose_name='Link to project')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Degree')),
                ('major', models.CharField(max_length=50, verbose_name='Major')),
                ('institution', models.CharField(max_length=50)),
                ('institutionURL', models.URLField()),
                ('from_year', models.DateField(verbose_name='From')),
                ('to_year', models.DateField(verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Skill')),
                ('level', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Role')),
                ('company', models.CharField(max_length=30, verbose_name='Company')),
                ('companyURL', models.URLField(verbose_name='Company website')),
                ('from_year', models.DateField(verbose_name='From')),
                ('to_year', models.DateField(verbose_name='To')),
                ('description', models.CharField(max_length=250, verbose_name='Company Description')),
            ],
        ),
    ]
