# Generated by Django 2.1.4 on 2018-12-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='from_year',
            field=models.CharField(max_length=10, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institutionURL',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=50, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_year',
            field=models.CharField(max_length=10, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='work',
            name='from_year',
            field=models.CharField(max_length=10, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='work',
            name='to_year',
            field=models.CharField(max_length=10, verbose_name='To'),
        ),
    ]
