# Generated by Django 2.1.4 on 2018-12-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20181221_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='CGPA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='education',
            name='scale',
            field=models.IntegerField(blank=True, default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='education',
            name='from_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(blank=True, max_length=100, verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='work',
            name='from_year',
            field=models.CharField(blank=True, max_length=10, verbose_name='From'),
        ),
    ]
