# Generated by Django 2.1.7 on 2019-02-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20181221_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Role')),
                ('institution', models.CharField(max_length=30, verbose_name='Institution')),
                ('institutionURL', models.URLField(verbose_name='Website')),
                ('from_year', models.CharField(blank=True, max_length=10, verbose_name='From')),
                ('to_year', models.CharField(max_length=10, verbose_name='To')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='scale',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='from_year',
            field=models.CharField(blank=True, max_length=20, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='work',
            name='to_year',
            field=models.CharField(max_length=20, verbose_name='To'),
        ),
    ]
