# Generated by Django 2.1.7 on 2019-02-23 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_graphics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graphics',
            new_name='Others',
        ),
    ]
