# Generated by Django 2.1.7 on 2019-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20190224_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(max_length=500, verbose_name='About'),
        ),
    ]
