# Generated by Django 2.1.7 on 2019-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20190224_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Membership Name')),
                ('status', models.BooleanField()),
                ('years', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
