# Generated by Django 2.1.7 on 2019-02-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_promembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promembership',
            name='years',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Total years'),
        ),
    ]
