# Generated by Django 2.1.7 on 2019-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20190226_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='promembership',
            name='institutionURL',
            field=models.URLField(default='#', verbose_name='Website'),
        ),
    ]
