# Generated by Django 2.1.7 on 2019-03-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_promembership_institutionurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='resume',
        ),
        migrations.AddField(
            model_name='about',
            name='resumeURL',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='promembership',
            name='status',
            field=models.BooleanField(verbose_name='Active'),
        ),
    ]
