# Generated by Django 2.1.7 on 2019-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20190313_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='resumeURL',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
