# Generated by Django 2.2.3 on 2019-07-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20190313_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
